### ISSUE TITLE
Unable to download the extension from marketplace

### ISSUE THREAD

**Issue by raswinraaj** [vfabing/AzureVm#13]
When i click on Get it for Free icon on https://marketplace.visualstudio.com/items?itemName=vfabing.AzureVirtualMachineManagerTask, I am getting 500 error. 
![image](https://user-images.githubusercontent.com/50330414/74904007-b26cd000-53d0-11ea-9b97-7261c40b6de9.png)

**Comment by vfabing** [comment]
Hi @raswinraaj, thank you for the notificaiton!

Unfortunately, I am afraid this error is not related to the extension in itself but rather to access of your account, or a more generic error from the marketplace.

Feel free to reach the `MarketplaceTeam` as written in the error, and don't hesitate to put me in copy for following the issue and see if I can help.

Best regards,

**Comment by vfabing** [comment]
Hi @raswinraaj did you manage to install the extension?

Let me close this issue as I don't think I am able to help you about this subject, but feel free to reopen it if I could be of any help!
